### ISSUE TITLE
[Feature] Turkish language support

### ISSUE THREAD

**Issue by ramazansancar** [datarhei/restreamer-ui#22]
Hello, I would like to support Turkish language translation. How can I provide this?

**Comment by ioppermann** [comment]
You can join the translation team at https://poeditor.com/join/project/ogATl3F48K

**Comment by ramazansancar** [comment]
Thanks, I sent a request.

**Comment by ramazansancar** [comment]
Hello @ioppermann, I made some of the translations, can you include them in the project?

**Comment by ramazansancar** [comment]
@ioppermann Thanks 🤩🥳

**Comment by ramazansancar** [comment]
Hello, I had a question while translating, can you help me?

Should we leave these parts in English or should we translate them?

![image](https://user-images.githubusercontent.com/8878055/212548546-8ec2cfd5-9a67-41d8-b850-972f6f62686a.png)

**Comment by ioppermann** [comment]
This should be translated too.

The `<0>...</0>` is a placeholder for a HTML tag. In this case it will be a link to the docs.

**Comment by ramazansancar** [comment]
Thanks fir information
