### ISSUE TITLE
Help buttons do not work in locales other than English

### ISSUE THREAD

**Issue by toby3d** [datarhei/restreamer-ui#24]
## What I do
* Setup the Restreamer instance, go through the initial configurations steps;
* Switching to any other locale (Russian in my case) via the switch in the upper right corner of the page;
* Press the icon button with a question mark on any screen;

## What I want to get
Redirects to the desired help page in the context of the current navigation location.

## What I get
Nothing happens. Errors in the web inspector console on every click.

Button on channel player:
```log
Uncaught TypeError: can't access property "en", e[e] is undefined
    t help.js:203
    RA help.js:219
    _ index.js:262
    React 11
help.js:203:1
```

Button on settings page:
```
Uncaught TypeError: can't access property "en", e[e] is undefined
    t help.js:203
    RA help.js:219
    L Settings.js:1184
    React 11
help.js:203:1
```

---

P.S. As someone who pays attention to accessibility in the web I strongly dislike that the redirections to the help pages are implemented through `<button>`, not `<a>`. But this is a topic for other issues, which I can arrange if it makes sense for the owners of the project.

**Comment by ioppermann** [comment]
Thanks for the bug report. This bug has been fixed.

The documentation is currently only available in English and German. If you select any other language in the UI, it will send you to the English version of the documentation.
