### ISSUE TITLE
Chromecast not working and how to correct it.

### ISSUE THREAD

**Issue by badincite** [datarhei/restreamer-ui#37]
Noticed awhile back Chromecast wasn't working. It appears the source origin was missing and the default receiver id is required. 

```
var config = {
	controls: true,
	poster: playerConfig.poster + '?t=' + String(new Date().getTime()),
	autoplay: autoplay ? 'muted' : false,
	muted: true,
	liveui: true,
	responsive: true,
	fluid: true,
	sources: [{ src: window.location.origin + '/' + playerConfig.source, type: 'application/x-mpegURL' }],
	plugins: {
		license: playerConfig.license,
		chromecast: {
			receiverApplicationId: 'CC1AD845'
		},
	},
};
```

**Comment by SuperGlobal** [comment]
@badincite Can you be more specific with the file(s) that you patched with this? I'm currently having some issues with the Chromecast as well and believe this issue has something to do with it.

Using Cactool I'm able to pass the stream M3U from restreamer directly to my Chromecast which would lead me to believe something like what you're pointing out is causing my issue.

**Comment by badincite** [comment]
@SuperGlobal  the video.js file here
https://github.com/datarhei/restreamer-ui/blob/main/public/_playersite/videojs.js

**Comment by badincite** [comment]
This still is an issue with the new update
