### ISSUE TITLE
Restreamer Settings "Check for updates" not aligned with documentation

### ISSUE THREAD

**Issue by utilsites** [datarhei/restreamer-ui#53]
Check the image, in the Restreamer UI Setting "Check for updates" there is a link to documentation that says "automatic updates".
It's not clear if this setting is just to show if there are new versions or to auto update like the documentation specifies.
I think it's just to check, as it didn't update automatically. So would be nice to fix the documentation.

![image](https://github.com/datarhei/restreamer-ui/assets/15893370/991e7efd-f106-46c8-ab6c-aef098b95f90)

**Comment by ioppermann** [comment]
Thanks for the hint. This has been fixed in the documentation: https://docs.datarhei.com/restreamer/installing/update
