### ISSUE TITLE
Change the core restreamer address destination

### ISSUE THREAD

**Issue by alfaputra27** [datarhei/restreamer-ui#66]
hello sir, i want to ask, i tried to install ui restreamer on my local computer, but i want to connect restreamer ui to restreamer core that i installed on vps. The question is, where do i change the url/core address in restreamer UI?

**Comment by ioppermann** [comment]
You can add the `address=...` query parameter to the UI. If your UI is running on e.g. `http://127.0.0.1:3000/` then add this query parameter with the address of the core, e.g. `http://127.0.0.1:3000/?address=https://address.to.your.vps:port`

**Comment by alfaputra27** [comment]
can i add progress bar when uploading loop source video sir. i have tried but the upload % value is not dynamic. please help me

**Comment by ioppermann** [comment]
Please open a new issue for the progress bar.
